### PR TITLE
fix: fallback for older versions of ox_inventory

### PR DESCRIPTION
**Pull request by 0xDEMXN**

### CODE REVIEW

**Review by konijn-x — APPROVED** [review]
Thanks for you contribution! 
❤️The ESX Team

**Comment by thelindat** [comment]
Pointless since people getting the official esx would already have the latest inventory

**Comment by 0xDEMXN** [comment]
> Pointless since people getting the official esx would already have the latest inventory

I'd agree with you but people asked support for this on ESX discord 🥲

**Comment by Esplike** [comment]
It's kinda pointless...

**Pull request closed without merging**
