### PR TITLE
esx_identity: fix NUI not loading on low-end pc

### PR DESCRIPTION
**Pull request by ITKewai**

### CODE REVIEW

**Comment by xj0le** [comment]
@Tinky124 lol, this fixed everything with the NUI...

**Comment by ITKewai** [comment]
> @Tinky124 lol, this fixed everything with the NUI...

yep only on potato pc 😂

**Comment by xj0le** [comment]
Good job bro, I didn't even check the code deeply.

I mean, if my PC is low-end and it still didn't load haha.

Ryzen 7 3700x, RTX 2080, 32GB RAM @3220MHz CL16

**Review by Mycroft-Studios — CHANGES_REQUESTED** [review]
looks good, but all prs should be to the development branch

**Review by Benzo00 — APPROVED** [review]

**Pull request merged**
