### PR TITLE
feat(locale): add esx:locale convar to server.cfg

### PR DESCRIPTION
**Pull request by CsokiHUN**
I added a new convar to server.cfg to easily set the language of the entire framework.
I changed Config.Locale to convar in all scripts
I hope to helpful this update

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi! @Benzo00 Pls merge this. We voted  in discord.

**Comment by mr-capy** [comment]
> Hi! @Benzo00 Pls merge this. We voted  in discord.

Now i started loved ur prs .
Nice one again sir.

**Review by Mycroft-Studios — APPROVED** [review]
This will be added soon :)

**Comment by Gellipapa** [comment]
@Mycroft-Studios Hi! What's up? :)

**Comment by Benzo00** [comment]
this is in now. made some changes thats why mycroft forced commited it

**Pull request closed without merging**
