### PR TITLE
Fix shitty multicharacter locales :(

### PR DESCRIPTION
**Pull request by TheFantomas**

### CODE REVIEW

**Review by Mycroft-Studios — CHANGES_REQUESTED** [review]
This should be using `Translate` not `_` since its post-1.8.5

**Comment by Benzo00** [comment]
Like mycroft said.

**Comment by TheFantomas** [comment]
I will fix it

**Comment by TheFantomas** [comment]
Done @Benzo00

**Review by Gellipapa — APPROVED** [review]
Tested and working. Thank you for PR. @TheFantomas

**Pull request merged**
