### PR TITLE
fix for spawning unlimited job vehicles

### PR DESCRIPTION
**Pull request by Taavi-AU**

### CODE REVIEW

**Review by TrymTube — APPROVED** [review]

**Review by bitpredator — APPROVED** [review]

**Comment by janbiehl** [comment]
Weird i created the same PR a few weekd ago. 
Somebody said that this fix breaks things for him, so i am not the only one with that error :)

**Comment by TrymTube** [comment]
> Weird i created the same PR a few weekd ago. Somebody said that this fix breaks things for him, so i am not the only one with that error :)

I have had this problem too I have put the fix in the Discord before I became Supporter nobody gave attention to it and I forgot

**Comment by Taavi-AU** [comment]
Didn't break anything for me

**Comment by Taavi-AU** [comment]
All it does is changes from checking true/false to 1 or 0

**Comment by janbiehl** [comment]
See here #565 .

By the way the same thing is broken for me in the ambulance job. It is exatly the same as with policejob

**Comment by Taavi-AU** [comment]
Yeah I fixed both, check the commits.

**Pull request merged**
