### PR TITLE
feat(v2): re-work for legacy

### PR DESCRIPTION
**Pull request by PsychoShock**
Let's try to make something from this without changing anything that will break old stuffs.

### CODE REVIEW

**Comment by PsychoShock** [comment]
I won't acually change anything on core for not breaking anything.

**Review by PsychoShock — COMMENTED** [review]
@Mycroft-Studios please test this one before merging. I will maybe even change the logic on this.

**Comment by PsychoShock** [comment]
I really need to think about a new logic on thread's without the `if CurrentAction then` since this is really old way to make thing's. I will finish this then will re-work on thread's.

**Review by faitti — APPROVED** [review]
LGTM!

**Review by konijn-x — APPROVED** [review]

**Review by konijn-x — CHANGES_REQUESTED** [review]
At esx_atm/config.lua, there is something wrong. 
`vector3(-386.733, 6045.953, 31.501},`
You start with ( and you closes it with }. 
-----------------------------------------------------------------------------------------

**Comment by PsychoShock** [comment]
After a big work and 2 month wait, no update. It's sadly, I was going try to help the project little.

**Comment by TheLazarusRising** [comment]
The person that handles and reviews the PRs is having issues with broken PC.
I haven't gotten an update on when they will be able to get a PC again.

So for now, it's just something we'll have to patiently wait on.

**Comment by PsychoShock** [comment]
Well, with all the new updates in the last two month everything has conflict. So I don't recommend merging it.

**Comment by Esplike** [comment]
Looking good @PsychoShock, Fix the conflicts though :0

**Comment by PsychoShock** [comment]
There's too many, it's most likely better to just make another PR. @TheLazarusRising after 2 month of waiting for a answer it's sad to restart everything.

**Comment by mcNuggets1** [comment]
Having so many unneeded changes in a commit is not necessarily a good thing.
Especially when editting the code style of ESX to your own, that's maybe something not everyone agrees on or wants to happen.

**Comment by PsychoShock** [comment]
> Having so many unneeded changes

what?

Also
> editting the code style of ESX to your own

is that even mean something???


Maybe you should learn that the only thing's changing here is the loop's and how code is call. That make no sens this comment.

**Comment by PsychoShock** [comment]
Will close this since weird people are starting a conversation here that doesn't make sens. @Esplike text me on Discord when you wanna work on the V2.

**Pull request closed without merging**
