### PR TITLE
Dutch translation for esx_weaponshop

### PR DESCRIPTION
**Pull request by HariboInc**
Can also create a database file if liked but the names will be unchanged because these are names.

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi!

Thanks for the German translation.

Change the title of the PR **feat(Dutch translation for esx_weaponshop)** thanks.

**Comment by HariboInc** [comment]
Netherlandssss :P

**Comment by Benzo00** [comment]
https://github.com/esx-framework/esx-legacy/issues/343 take a look on this

**Comment by Benzo00** [comment]
reopen this with a proper title

**Pull request closed without merging**
