### PR TITLE
fix(esx_vehicle): fixed invalid Lua in rental vehicle server-side code

### PR DESCRIPTION
**Pull request by GoatG33k**

### CODE REVIEW

**Comment by DokaDoka** [comment]
This was not invalid, esx_vehicleshop has been upgraded to use lua 5.4

**Comment by DokaDoka** [comment]
jesus... 
https://github.com/citizenfx/lua/blob/luaglm-dev/cfx/README.md

**Comment by GoatG33k** [comment]
Yeah, I'm not really a fan of having code that throws errors in the majority of code editors, and isn't supported by the Lua ecosystem... just so you can save like five characters lol

**Comment by RockySouthpaw** [comment]
> Yeah, I'm not really a fan of having code that throws errors in the majority of code editors, and isn't supported by the Lua ecosystem... just so you can save like five characters lol

Welcome to the land of micro optimizations that degrades readability all to reduce some arbitrary **ms** number.

**Comment by DokaDoka** [comment]
whatever, the syntax is valid, if your linter doesn't keep up then that's your problem, and I guess esx's now

**Pull request merged**
