### PR TITLE
Proper localization.

### PR DESCRIPTION
**Pull request by xj0le**

### CODE REVIEW

**Review by Mycroft-Studios — CHANGES_REQUESTED** [review]
this removes a feature, that was added because it was heavily requested. returning english is an intended feature that was added after we changed ALL translations to be a convar

**Comment by CsokiHUN** [comment]
i dont understand you why remove this. Its good feature, if locale not exists

**Comment by xj0le** [comment]
Try to use any other language than English.

**Comment by TheFarFantomas** [comment]
> Try to use any other language than English.

Its impossible because some esx dev dont check his fucking commits :)

**Comment by fsocietystudios** [comment]
Hey. I think removing the feature of fall-backing into English is pointless.
Thanks for your PR, but, at this point we are not gonna merge this PR and remove this feature.

**Comment by TheFantomas** [comment]
DID YOU FUCKING TRY TO CHANGE LOCALE TO ANOTHER LANGUAGE??? Like cs,es? GJ Esx Team :DDDDDDDDDDD
image

**Comment by Gellipapa** [comment]
@TheFarFantomas Hi! Thank you for report this issue, other times, be a little nicer and tell me what your problem is.

**Pull request closed without merging**
