### PR TITLE
New year licenses 🎈 🎈 🎈 

### PR DESCRIPTION
**Pull request by TheFantomas**

### CODE REVIEW

**Review by JackDUpModZ — APPROVED** [review]

**Comment by Gellipapa** [comment]
Hi! @TheFantomas Thank you for your attention but fix merge conflict please :) Happy new year :)

**Comment by Mojito-Fivem** [comment]
Duplicate of #798
Closed.

**Comment by TheFantomas** [comment]
> Duplicate of #798 Closed.

Duplicate? :D I replace 2022 to 2023 in all licenses :D Thats not duplicate :D

**Comment by TheFantomas** [comment]
Sorry i delete esx-legacy fork 😂

**Pull request merged**
