### PR TITLE
feat: new resource to store health and armour

### PR DESCRIPTION
**Pull request by d3rp-jsx**
Hello, this is a resource I released sometime ago and it's core for RP servers!
Hope this will be useful and feel free to request any edit if needed.

### CODE REVIEW

**Comment by MrNewb** [comment]
Please dont do it this way @d3rp-jsx do it through basic needs so its in the same table. as other information already gets pulled, also eliminates the need for things like ```RegisterNetEvent('esx:onPlayerSpawn')
AddEventHandler('esx:onPlayerSpawn', function()
  local playerId = source
  local xPlayer = ESX.GetPlayerFromId(playerId)

  if xPlayer ~= nil then
    MySQL.Async.fetchAll(LoadHealthNArmour, {xPlayer.identifier}, function(data)
      if data[1].health ~= nil and data[1].armour ~= nil then
        TriggerClientEvent('esx_healthnarmour:set', playerId, data[1].health, data[1].armour)
      end
    end)
  end
end)```

**Comment by d3rp-jsx** [comment]
> Please dont do it this way @d3rp-jsx do it through basic needs so its in the same table. as other information already gets pulled, also eliminates the need for things like ````RegisterNetEvent('esx:onPlayerSpawn') AddEventHandler('esx:onPlayerSpawn', function() local playerId = source local xPlayer = ESX.GetPlayerFromId(playerId)
> 
> if xPlayer ~= nil then MySQL.Async.fetchAll(LoadHealthNArmour, {xPlayer.identifier}, function(data) if data[1].health ~= nil and data[1].armour ~= nil then TriggerClientEvent('esx_healthnarmour:set', playerId, data[1].health, data[1].armour) end end) end end)````

Basic needs is not designed for that, I can't understand what you are saying honestly, two columns won't be any issue.

**Comment by MrNewb** [comment]
by default but its basic design it to save and load a table, why add extra when you already have something doing checks constantly.  my point with the codeblock that doesn't look like a code block is you are doing additional mysql calls when it could be done elsewhere without the need for an additional resource.  Basic needs/status can do this instead.

**Comment by d3rp-jsx** [comment]
You gave yourself the answer, I would never add this to status or basic needs because it doesn't need to be constantly checked and it would be a useless burden to the server.

**Comment by Luke20201** [comment]
Hi,

Thank you for taking the time to create a new resource for ESX! We truly appreciate every commit made to the Repo, in hopes of improving the Framework for everyone!

Unfortunately, however, I believe this will be more fitting as a release on the FiveM Forum's, rather than a part of the ESX repo.

I'm sorry we are unable to approve this, but great work either way!

**Pull request closed without merging**
