### PR TITLE
refactor(esx_shops): Add export for OpenShop and make function localized

### PR DESCRIPTION
**Pull request by FjamZoo**
Makes the shops globalized function to a localized function very small change in terms of optimization however its just better code practice.

### CODE REVIEW

**Comment by FjamZoo** [comment]
Added a export to shop Mycroft told me if you flame me then its his fault not mine

This OpenShop export can be opened by doing this

exports['esx_shop']:OpenShop(Zone) -- The zone is a variable you want to pass to the shop, look inside the shop client file to look more indepth how this function works.

**Comment by FjamZoo** [comment]
for anyone reading this and asking why would we want to make function localised?

localized functions run slightly faster and shows good code practice for new developers looking into how to do stuff.

(Only do this in single files or files where the function is only being accessed in a single file and the local functions have to be above where it gets called like normal Functions)

**Comment by TheSpaceGamerV2** [comment]
> for anyone reading this and asking why would we want to make function localised?
> 
> localized functions run slightly faster and shows good code practice for new developers looking into how to do stuff.
> 
> (Only do this in single files or files where the function is only being accessed in a single file and the local functions have to be above where it gets called like normal Functions)

Sure ur right anyway in this case OpenShopMenu() do not need to be global.

**Comment by TheLazarusRising** [comment]
If you want to finish this PR, then this needs to be done for every resource, along with proper structure for the commit message:

https://www.conventionalcommits.org/en/v1.0.0/

**Pull request closed without merging**
