### PR TITLE
fix errors and warnings across esx-legacy

### PR DESCRIPTION
**Pull request by thelindat**

### CODE REVIEW

**Comment by thelindat** [comment]
Going to do the inventory stuff separately.

@Mycroft-Studios

**Comment by Mycroft-Studios** [comment]
👍🏼 , will have it tested. looking over the code it seems fine, although, for the Wait Changes, wouldn`t it be better to add sleeps to some of them?

**Comment by thelindat** [comment]
To quote bubble
> Wait will round to the nearest frame (as it’s tick-based) so all you’re doing here is causing problems for anyone with over 200 FPS at no noticeable other gain.
>
> If you want to run something every frame, use 0, don’t try to be clever with values between 1 and 15 or so.

**Review by PsychoShock — APPROVED** [review]
Doesn't really change anything so just by looking at it, code will work. It's small improvements. 👍

**Comment by Mycroft-Studios** [comment]
> To quote bubble
> 
> > Wait will round to the nearest frame (as it’s tick-based) so all you’re doing here is causing problems for anyone with over 200 FPS at no noticeable other gain.
> > If you want to run something every frame, use 0, don’t try to be clever with values between 1 and 15 or so.

👍🏼 😄

**Pull request merged**
