### PR TITLE
fix(esx_property): wrong datastore usage

### PR DESCRIPTION
**Pull request by FAr18**
Currently, when the resource starts, it creates redundant rows in `datastore_data`.
The datastore `property` should be non-shared, and we don't need to insert data into `datasotre_data`.

### CODE REVIEW

**Review by AstroNext — APPROVED** [review]

**Comment by Mycroft-Studios** [comment]
it should be shared, since it has no owner

**Comment by FAr18** [comment]
i only found it for the player's wardrobe, or does it have other uses?
(not even any way to trigger `esx_datastore:getSharedDataStore`)

and it does insert duplicate and useless rows inside my database

**Comment by Mycroft-Studios** [comment]
> or does it have other uses?
nope, the way it works is shit, but it works that way to ensure peoples outfits transfer to v2

**Comment by FAr18** [comment]
got it, thanks for the reply

**Pull request closed without merging**
