### PR TITLE
Dutch translation for esx_multicharacters

### PR DESCRIPTION
**Pull request by HariboInc**

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi!

Thanks for the German translation.

Change the title of the PR **feat(Dutch translation for esx_multicharacters)** thanks.

**Review by Gellipapa — COMMENTED** [review]
I think okey pls change title :)

**Comment by HariboInc** [comment]
Like that title? And what a disgrace, German is German and Dutch is Dutch hahaha :P Dutch from the Netherlands

**Comment by Gellipapa** [comment]
> Like that title? And what a disgrace, German is German and Dutch is Dutch hahaha :P Dutch from the Netherlands

Ohh sorry lord, i very tired when write this.

**Comment by HariboInc** [comment]
But like the title as in creating a new file or this title?

**Comment by Benzo00** [comment]
https://github.com/esx-framework/esx-legacy/issues/343 take a look on this

**Comment by Gellipapa** [comment]
> But like the title as in creating a new file or this title?

You can change PR title click right corner edit button and change title.

**Comment by Benzo00** [comment]
reopen this when u have fixed the pr title!

**Comment by HariboInc** [comment]
Alright this or feat? Because it's not a new code.

**Pull request closed without merging**
