### PR TITLE
refactor(esx_banking)

### PR DESCRIPTION
**Pull request by Rav3n95**
- Rewrite on client side
- Removed unused debug config option
- New ShowMarker config option

### CODE REVIEW

**Comment by CsokiHUN** [comment]
@Rav3n95 check my changes please

**Review by CsokiHUN — APPROVED** [review]

**Comment by Rav3n95** [comment]
We have to close the UI on death event too then

**Comment by Rav3n95** [comment]
We have to close the UI on death event too then

**Comment by Rav3n95** [comment]
Look good to me

**Pull request merged**
