### PR TITLE
refactor(esx_status): no more need server classes

### PR DESCRIPTION
**Pull request by AstroNext**

### CODE REVIEW

**Review by Mycroft-Studios — CHANGES_REQUESTED** [review]
WTF, u just removed the core of status xD

**Comment by FilipeCuco** [comment]
> WTF, u just removed the core of status xD

it is not even loading fxmanifest.lua

**Comment by Gellipapa** [comment]
Hi! @AstroNext What is current status for pull request?  I checked files and i find server/client side CreateStatus functions but fxmanifest don't include these and interesting Config files load only server side, but CreateStatus only use client side. 

Please take a look and we will clear things up :)

**Comment by AstroNext** [comment]
> 

I check codes again,
My experience in this resource tell me that need more edit ( usage on each status or tick when call status function)
this server class is exist in old status resource but not used in server side .

**Comment by Gellipapa** [comment]
@AstroNext  Yes, I saw that the server page is not in use but the config page is. Can you see if you delete the fxmanifest and fix the status? I'm also thinking of older ESX. Backwards compatibility is important.

**Comment by Gellipapa** [comment]
@AstroNext Hi! What's up this refactor? Did you manage to fix it?

**Comment by TheFantomas** [comment]
> @AstroNext Hi! What's up this refactor? Did you manage to fix it?

It looks like it won't fix anything :D That's why I'd probably close it so it won't be useless here :D On the other hand, what is backward compatibility for? However, this part was not started before :D After all, no one could use it without some modifications

**Comment by Gellipapa** [comment]
Yes @TheFantomas. I close if you refactor or rewrite status delete unused files :)

**Pull request closed without merging**
