### PR TITLE
refactor(esx_service/server/main.lua) Added condition to handle MaxService when set to -1

### PR DESCRIPTION
**Pull request by lexinor**
- I added a condition to handle when we set MaxService to -1. Because I was not able to take a service when it was set to -1

### CODE REVIEW

**Comment by tony-stark-17** [comment]
image
This is how esx_policejob does it which is how it should be done in scripts.

**Comment by lexinor** [comment]
> image This is how esx_policejob does it which is how it should be done in scripts.

So I guess when you put -1 it should not work so ?

**Comment by lexinor** [comment]
Any news ?

**Comment by lexinor** [comment]
I'm closing that PR

**Pull request closed without merging**
