### PR TITLE
fix(esx_property): fixed locales and SQL queries

### PR DESCRIPTION
**Pull request by dolutattoo**

### CODE REVIEW

**Comment by Benzo00** [comment]
https://github.com/esx-framework/esx-legacy/pulls take a look on this

**Review by MantysCZ — APPROVED** [review]

**Comment by dolutattoo** [comment]
> #343 take a look on this

Commits are correctly named, does the PR name have to be named like this too?

**Comment by roadtosixx** [comment]
> > #343 take a look on this
> 
> Commits are correctly named, does the PR name have to be named like this too?

Yes

**Comment by dolutattoo** [comment]
Why that? Once merged the name is not visible anymore...
Anyway just give me the name cause idk how to name it since this PR includes different things.

**Pull request merged**
