### PR TITLE
fix(esx_ambulancejob/client/vehicle.lua): fixed vehicle storage bug

### PR DESCRIPTION
**Pull request by janbiehl**
A vehicle from ambulancejob could be spawned from garage for a unlimited amount. The UI did always tell that the vehicle was stored, no matter what the entry in the Database was stating.

Now after spawning the vehicle, the state is correctly shown in the UI. Multiple spawns are not possible anymore.

### CODE REVIEW

**Comment by iSentrie** [comment]
it breaks for me everything

**Comment by janbiehl** [comment]
> it breaks for me everything

This is crazy, for us it is the only way how we get things to work like expected. In which way it breaks things on your side? What do you see? What do you expect?

**Comment by iSentrie** [comment]
it shows that all vehicles are taken out and i cannot get any. :D

**Comment by janbiehl** [comment]
> it shows that all vehicles are taken out and i cannot get any. :D

For me this is the expected behaviour, a car that is not properly stored in the garage will be shown as impounded. You then have to pay the impound at a towing station. You will get your vehicle back, and you are able to store it back in the garage. 

Without my changes you can take one and the same car out of the garage over and over again. So everybody could drive the same car with the same number plate. This cant be the desired behaviour of this.

**Comment by iSentrie** [comment]
> > it shows that all vehicles are taken out and i cannot get any. :D
> 
> For me this is the expected behaviour, a car that is not properly stored in the garage will be shown as impounded. You then have to pay the impound at a towing station. You will get your vehicle back, and you are able to store it back in the garage.
> 
> Without my changes you can take one and the same car out of the garage over and over again. So everybody could drive the same car with the same number plate. This cant be the desired behaviour of this.

thats how it works without any changes for me, with your changes i cant get a vehicle :D

**Comment by janbiehl** [comment]
> > > it shows that all vehicles are taken out and i cannot get any. :D
> > 
> > 
> > For me this is the expected behaviour, a car that is not properly stored in the garage will be shown as impounded. You then have to pay the impound at a towing station. You will get your vehicle back, and you are able to store it back in the garage.
> > Without my changes you can take one and the same car out of the garage over and over again. So everybody could drive the same car with the same number plate. This cant be the desired behaviour of this.
> 
> thats how it works without any changes for me, with your changes i cant get a vehicle :D thats actually super weird

weird, i think i will close this. As i won't break things for others, maybe there is something strange on our side.

**Pull request closed without merging**
