### PR TITLE
refactor(esx_society)

### PR DESCRIPTION
**Pull request by CsokiHUN**

### CODE REVIEW

**Review by Gellipapa — APPROVED** [review]
Good job @CsokiHUN :)

**Comment by Gellipapa** [comment]
@CsokiHUN Hi! Please fix merge conflict after we can merge! Thank you for help :)

**Comment by CsokiHUN** [comment]
# DONE!

**Comment by Gellipapa** [comment]
@CsokiHUN  Thank you for fast reaction :)

**Pull request merged**
