### PR TITLE
feat(es_extended/locales/my.lua) Add my locale

### PR DESCRIPTION
**Pull request by AAMSYAR46**
Malaysian languages

### CODE REVIEW

**Review by TheFantomas — APPROVED** [review]

**Comment by Gellipapa** [comment]
Hi! @AAMSYAR46  There are some gaps compared to the latest version, please include them. A good method is to use a text difference page. For example: https://text-compare.com/.

If you manage to solve it, please report back.

**Comment by AAMSYAR46** [comment]
> Hi! @AAMSYAR46 There are some gaps compared to the latest version, please include them. A good method is to use a text difference page. For example: https://text-compare.com/.
> 
> If you manage to solve it, please report back.

this?
image

**Comment by Gellipapa** [comment]
> 
Yes, compare and complete the lines.

**Comment by AAMSYAR46** [comment]
> > 
> Yes, compare and complete the lines.

all the line? ok

**Comment by Gellipapa** [comment]
@AAMSYAR46 Hi! Please update your branch latest state and check that it works afterwards.

**Comment by TheFantomas** [comment]
And then it will be okey...

**Comment by Gellipapa** [comment]
Hi! @AAMSYAR46 It's not okey please update your branch and translate missing texts. 

<html>
<body>


['command_giveammo_noweapon_found'] = '%s does not have that weapon', |   |
-- | --
  ['command_giveammo_weapon'] = 'Weapon name',
  ['command_giveammo_ammo'] = 'Ammo Quantity', 
  ['tpm_nowaypoint'] = 'No Waypoint Set.', 
  ['tpm_success'] = 'Successfully Teleported',
  ['noclip_message'] = 'Noclip has been %s',
  ['enabled'] = '~g~enabled~s~', 
  ['disabled'] = '~r~disabled~s~',

</body>
</html>

**Comment by Benzo00** [comment]
No fixes yet made

**Pull request closed without merging**
