### PR TITLE
fix nil index value

### PR DESCRIPTION
**Pull request by Gellipapa**
Fix #724

### CODE REVIEW

**Review by TheFantomas — APPROVED** [review]
Finally someone who understood that this is really a problem :) Not someone who will say that it's useless even though they absolutely don't know what this "shit" that I don't know who added this but is 🤦

**Comment by Gellipapa** [comment]
> Finally someone who understood that this is really a problem :) Not someone who will say that it's useless even though they absolutely don't know what this "shit" that I don't know who added this but is 🤦

HI! @TheFantomas @Mycroft-Studios doing a refactor but no problem he don't test other laungages. Corrected and will be added soon :)

**Comment by TheFantomas** [comment]
> > Finally someone who understood that this is really a problem :) Not someone who will say that it's useless even though they absolutely don't know what this "shit" that I don't know who added this but is 🤦
> 
> HI! @TheFantomas @Mycroft-Studios doing a refactor but no problem he don't test other laungages. Corrected and will be added soon :)

In my opinion, this is quite a big problem :D When I do something new, should I test it or not? :D It doesn't matter :D Hopefully it will be fine after this update...

**Comment by Gellipapa** [comment]
> 

Of course that's normal but you may have forgotten, you may have made a mistake.

**Comment by TheFantomas** [comment]
> > 
> 
> Of course that's normal but you may have forgotten, you may have made a mistake.

Yes, if he wasn't the one who mocks people for making a mistake here. Not a word is said against him :D But now that he has made a mistake, he prefers to sit in the corner and not say anything

**Comment by Gellipapa** [comment]
#829 recreate pull request because dev not updated!

**Pull request closed without merging**
