### PR TITLE
refactor(esx_legacy): Converted all backtick usages to GetHashKey()

### PR DESCRIPTION
**Pull request by GoatG33k**
For FiveM Lua linting compatibility

### CODE REVIEW

**Comment by thelindat** [comment]
Fix your Lua linting instead of removing valid CfxLua syntax..

**Comment by EvanDarwin** [comment]
I don't have the time at the moment, feel free to contribute it yourself though!

**Comment by GoatG33k** [comment]
@thelindat Feel free to contribute it yourself, I don't have the time nor willpower to do it. Not to mention, both are valid.

**Comment by GoatG33k** [comment]
> "so it will not break anything"? 

Could you describe what it breaks exactly? To the best of my knowledge there is no functional difference between the two.

**Comment by Blumlaut** [comment]
> To the best of my knowledge there is no functional difference between the two.
GetHashKey is by nature slower. it's also less clean, there is no functional reason to use this compared to just fixing your linter

**Pull request merged**
