### PR TITLE
vehicle properties #285, fix esx_garage and NUI error on esx_identity

### PR DESCRIPTION
**Pull request by Slewog**
Try to fix the issues open on #285

### CODE REVIEW

**Comment by Slewog** [comment]
Let me know that fix the bug ;)

**Comment by Benzo00** [comment]
Did you actually try this before making a pr?

**Comment by Slewog** [comment]
Yes it's working on my dev server but i use the release 1.6.0 actually on my server. Why? Do you have an error with the pr?
________________________________
De : Benzo ***@***.***>
Envoyé : dimanche 5 juin 2022, 01:14
À : esx-framework/esx-legacy ***@***.***>
Cc : Slewog ***@***.***>; Author ***@***.***>
Objet : Re: [esx-framework/esx-legacy] vehicle properties #285 and NUI error on esx_identity (PR #293)


Did you actually try this before making a pr?

**Comment by iSentrie** [comment]
why closed it supposed to be a fix for #285 too

**Comment by Slewog** [comment]
Why you closed a pr who fix a bug ?

**Comment by Slewog** [comment]
Can i re-create the pr or it will be closed again?

**Comment by Slewog** [comment]
The fix about esx-identity is about this error, i got this error just after click on the button create
 
https://imgur.com/a/0rranwC

**Comment by Slewog** [comment]
And the fix for esx_garage is about this error

image

**Comment by iSentrie** [comment]
Tested vehicle properties fix, works just fine ✅

**Comment by Slewog** [comment]
Thank's to apply my pr ;)

**Comment by Benzo00** [comment]
esx_garage already fixed

**Comment by FBFezz** [comment]
Vehicle Properties working correctly 👍

**Comment by FBFezz** [comment]
Upon further testing vehicle liveries still don't save

**Comment by Slewog** [comment]
I close the PR because MyCroft merged the fix on one of his commits ;)

**Pull request closed without merging**
