### PR TITLE
refactor: jquery removal and formatting

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Review by CsokiHUN — APPROVED** [review]
Finally someone who is not a jquery supporter❤️

**Comment by MoskalykA** [comment]
> Finally someone who is not a jquery supporter❤️

Godspeed to me from this

**Comment by TheFantomas** [comment]
> Finally someone who is not a jquery supporter❤️

jquery is old shit :DDD

**Comment by Gellipapa** [comment]
Hi! @MoskalykA Thank you for pull request. Wait, they haven't used jquery yet, they just looked at dom loading :) Nice :)

**Pull request merged**
