### PR TITLE
Added support for future inventory configurations & added multiple generic event names.

### PR DESCRIPTION
**Pull request by meta-hub**

### CODE REVIEW

**Comment by Destructor** [comment]
❤️

**Comment by TheLazarusRising** [comment]
I will review this when I am able to access the internet on my PC. Sorry for the delay, but it was an unforeseen hardware failure, and the router isn't cheap, at least not for me.

**Comment by JohnnyS** [comment]
Any update on this?

**Comment by mcNuggets1** [comment]
Am I blind or wtf are you doing in esx_identity cl file?

**Comment by Mycroft-Studios** [comment]
was added in [Commit ef6b66ab3ea9dcdbfc7f88d607cb75750f43b81f](https://github.com/esx-framework/esx-legacy/commit/ef6b66ab3ea9dcdbfc7f88d607cb75750f43b81f)

**Pull request closed without merging**
