### PR TITLE
fix and refactor(esx_taxijob)

### PR DESCRIPTION
**Pull request by Gellipapa**
fix(list car in context menu title is undefined)
fix(put stock functionality)
refactor(client and server side add error handlings, check empty tables)
add(new text in locales)

### CODE REVIEW

**Review by bitpredator — APPROVED** [review]
Everything works fine

**Review by Rav3n95 — APPROVED** [review]

**Comment by TheFantomas** [comment]
Looks good to me. The only problem I have with everyone's access is that they don't put the new locales in all files :D You can probably imagine how annoying it is to find these things :D So I would ask them to put locales in everything.

In this format please
['empty_garage'] = 'No vehicle in the garage!', --Not translated

**Comment by JackDUpModZ** [comment]
@Gellipapa Need to fix conflicts please.

**Comment by Gellipapa** [comment]
Reopen if I get there :)

**Comment by Unavarage** [comment]
There is everything in the locale as I tried it in english and almost every language, the thing is that is still remains undefined, so the prolem is not in the locales but in the script inself.

**Comment by Gellipapa** [comment]
> 

Hi! This is issue closed because we rewrite esx_taxijob we do not fixes.

**Pull request closed without merging**
