### PR TITLE
build: remove esx_phone

### PR DESCRIPTION
**Pull request by jbdevic**

### CODE REVIEW

**Comment by FilipeCuco** [comment]
do you have a new phone to add to esx?

**Comment by jbdevic** [comment]
for the moment no
the phone will be moved to a different repo but no longer by default because nobody uses it

**Comment by MoskalykA** [comment]
Personally I propose to keep it but try to improve it over time

**Review by CsokiHUN — APPROVED** [review]

**Comment by CsokiHUN** [comment]
If this is removed, we will add [npwd](https://github.com/project-error/npwd) support instead

**Review by Rav3n95 — APPROVED** [review]

**Comment by Gellipapa** [comment]
> If this is removed, we will add [npwd](https://github.com/project-error/npwd) support instead

+1 but then you have to add the job notification module.

**Review by Benzo00 — APPROVED** [review]

**Pull request merged**
